version: '3'
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile.API
        ports:
            - '80:80'
            - '443:443'
        depends_on:
            - mydb
    worker:
        build:
            context: .
            dockerfile: Dockerfile.MachineStatusService
        depends_on:
            - mydb
    mydb:
        image: postgres
        volumes:
            - 'db-data:/var/lib/postgresql/data'
        ports:
            - '5432:5432'
volumes:
    db-data:
        driver: local
